### PR TITLE
Merge panama-vector:master

### PR DESCRIPTION
**Pull request by Bhavana-Kilambi**
Merge panama-vector:master into panama-vector:vectorInstrinsics
    
    Resolved merge conflicts in the following files -
    
               .jcheck/conf
               src/hotspot/cpu/aarch64/aarch64.ad
               src/hotspot/cpu/aarch64/aarch64_neon.ad
               src/hotspot/cpu/aarch64/aarch64_neon_ad.m4
               src/hotspot/cpu/aarch64/aarch64_sve.ad
               src/hotspot/cpu/aarch64/aarch64_sve_ad.m4
               src/hotspot/cpu/aarch64/assembler_aarch64.hpp
               src/hotspot/cpu/aarch64/c2_MacroAssembler_aarch64.hpp
               src/hotspot/cpu/x86/assembler_x86.cpp
               src/hotspot/cpu/x86/assembler_x86.hpp
               src/hotspot/cpu/x86/c2_MacroAssembler_x86.cpp
               src/hotspot/cpu/x86/c2_MacroAssembler_x86.hpp
               src/hotspot/cpu/x86/macroAssembler_x86.cpp
               src/hotspot/cpu/x86/macroAssembler_x86.hpp
               src/hotspot/cpu/x86/matcher_x86.hpp
               src/hotspot/cpu/x86/stubGenerator_x86_64.cpp
               src/hotspot/cpu/x86/stubRoutines_x86.cpp
               src/hotspot/cpu/x86/vm_version_x86.cpp
               src/hotspot/cpu/x86/vm_version_x86.hpp
               src/hotspot/cpu/x86/x86.ad
               src/hotspot/share/adlc/formssel.cpp
               src/hotspot/share/classfile/vmIntrinsics.hpp
               src/hotspot/share/opto/c2compiler.cpp
               src/hotspot/share/opto/classes.hpp
               src/hotspot/share/opto/library_call.cpp
               src/hotspot/share/opto/library_call.hpp
               src/hotspot/share/opto/node.hpp
               src/hotspot/share/opto/subnode.hpp
               src/hotspot/share/opto/superword.cpp
               src/hotspot/share/opto/vectorIntrinsics.cpp
               src/hotspot/share/opto/vectornode.cpp
               src/hotspot/share/opto/vectornode.hpp
               src/hotspot/share/prims/vectorSupport.cpp
               src/hotspot/share/runtime/vmStructs.cpp
               src/java.base/share/classes/jdk/internal/misc/X-ScopedMemoryAccess.java.template
               src/java.base/share/classes/jdk/internal/vm/vector/VectorSupport.java
               src/java.base/share/classes/module-info.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/AbstractSpecies.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/AbstractVector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Byte128Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Byte256Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Byte512Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Byte64Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/ByteMaxVector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/ByteVector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Double128Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Double256Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Double512Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Double64Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/DoubleMaxVector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/DoubleVector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Float128Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Float256Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Float512Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Float64Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/FloatMaxVector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/FloatVector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Int128Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Int256Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Int512Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Int64Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/IntMaxVector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/IntVector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Long128Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Long256Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Long512Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Long64Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/LongMaxVector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/LongVector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Short128Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Short256Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Short512Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Short64Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/ShortMaxVector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/ShortVector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/Vector.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/VectorIntrinsics.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/VectorSpecies.java
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/X-Vector.java.template
               src/jdk.incubator.vector/share/classes/jdk/incubator/vector/X-VectorBits.java.template
               src/jdk.internal.vm.ci/share/classes/jdk.vm.ci.amd64/src/jdk/vm/ci/amd64/AMD64.java
               test/hotspot/gtest/aarch64/aarch64-asmtest.py
               test/hotspot/gtest/aarch64/asmtest.out.h
               test/hotspot/jtreg/compiler/vectorapi/TestIntrinsicBailOut.java
               test/hotspot/jtreg/compiler/vectorapi/VectorMemoryAlias.java
               test/hotspot/jtreg/compiler/vectorapi/VectorRebracket128Test.java
               test/hotspot/jtreg/compiler/vectorapi/reshape/tests/TestVectorDoubleExpandShrink.java
               test/hotspot/jtreg/compiler/vectorapi/reshape/tests/TestVectorExpandShrink.java
               test/hotspot/jtreg/compiler/vectorapi/reshape/utils/VectorReshapeHelper.java
               test/hotspot/jtreg/compiler/vectorization/TestPopCountVectorLong.java
               test/jdk/jdk/incubator/vector/AbstractVectorLoadStoreTest.java
               test/jdk/jdk/incubator/vector/Byte128VectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/Byte128VectorTests.java
               test/jdk/jdk/incubator/vector/Byte256VectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/Byte256VectorTests.java
               test/jdk/jdk/incubator/vector/Byte512VectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/Byte512VectorTests.java
               test/jdk/jdk/incubator/vector/Byte64VectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/Byte64VectorTests.java
               test/jdk/jdk/incubator/vector/ByteMaxVectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/ByteMaxVectorTests.java
               test/jdk/jdk/incubator/vector/Double128VectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/Double256VectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/Double512VectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/Double64VectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/DoubleMaxVectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/Float128VectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/Float256VectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/Float512VectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/Float64VectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/FloatMaxVectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/Int128VectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/Int128VectorTests.java
               test/jdk/jdk/incubator/vector/Int256VectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/Int256VectorTests.java
               test/jdk/jdk/incubator/vector/Int512VectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/Int512VectorTests.java
               test/jdk/jdk/incubator/vector/Int64VectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/Int64VectorTests.java
               test/jdk/jdk/incubator/vector/IntMaxVectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/IntMaxVectorTests.java
               test/jdk/jdk/incubator/vector/Long128VectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/Long128VectorTests.java
               test/jdk/jdk/incubator/vector/Long256VectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/Long256VectorTests.java
               test/jdk/jdk/incubator/vector/Long512VectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/Long512VectorTests.java
               test/jdk/jdk/incubator/vector/Long64VectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/Long64VectorTests.java
               test/jdk/jdk/incubator/vector/LongMaxVectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/LongMaxVectorTests.java
               test/jdk/jdk/incubator/vector/Short128VectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/Short128VectorTests.java
               test/jdk/jdk/incubator/vector/Short256VectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/Short256VectorTests.java
               test/jdk/jdk/incubator/vector/Short512VectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/Short512VectorTests.java
               test/jdk/jdk/incubator/vector/Short64VectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/Short64VectorTests.java
               test/jdk/jdk/incubator/vector/ShortMaxVectorLoadStoreTests.java
               test/jdk/jdk/incubator/vector/ShortMaxVectorTests.java
               test/jdk/jdk/incubator/vector/VectorReshapeTests.java
               test/jdk/jdk/incubator/vector/templates/X-LoadStoreTest.java.template
               test/micro/org/openjdk/bench/jdk/incubator/vector/MaskCastOperationsBenchmark.java
               test/micro/org/openjdk/bench/jdk/incubator/vector/MemorySegmentVectorAccess.java
               test/micro/org/openjdk/bench/jdk/incubator/vector/TestLoadStoreBytes.java
               test/micro/org/openjdk/bench/jdk/incubator/vector/TestLoadStoreShorts.java

"test/jdk/incubator/vector" and "test/hotspot/compiler/vectorapi" JTREG tests passed on an SVE system.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Reviewers
 * [Jatin Bhateja](https://openjdk.org/census#jbhateja) (@jatin-bhateja - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/panama-vector.git pull/215/head:pull/215` \
`$ git checkout pull/215`

Update a local copy of the PR: \
`$ git checkout pull/215` \
`$ git pull https://git.openjdk.org/panama-vector.git pull/215/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 215`

View PR using the GUI difftool: \
`$ git pr show -t 215`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/panama-vector/pull/215.diff">https://git.openjdk.org/panama-vector/pull/215.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/panama-vector/pull/215#issuecomment-1527268379)

### CODE REVIEW

**Comment by Bhavana-Kilambi** [comment]
The reason I am trying to merge "panama-vector:master" with "panama-vector:vectorIntrinsics" is so that we get the updated *ad files for aarch64 in the "vectorIntrinsics" branch and eventually the "vectorIntrinsics+fp16" branch where I would like to add some FP16 related aarch64 backend patches. Plan is to merge "vectorIntrinsics" with "vectorIntrinsics+fp16" branch once this PR is integrated into the "vectorIntrinsics" branch. Since the aarch64 *ad files have gone through some major changes from the version currently supported in the "vectorIntrinsics+fp16" branch, I would like to update the branch before adding any backend patches to it. 

Please help review this PR. Thank you ..

**Comment by jatin-bhateja** [comment]
I have stated regression run with merge patch will respond back.

**Review by jatin-bhateja — APPROVED** [review]
LGTM all tests passed.

**Pull request closed without merging**
