### PR TITLE
8264321: Create a separate library for x86 Intel SVML assembly intrinsics

### PR DESCRIPTION
**Pull request by sviswa7**
Intel Short Vector Math Library (SVML) based intrinsics in native x86 assembly provide optimized implementation for Vector API transcendental and trigonometric methods.
These methods can be built into a separate library instead of being part of libjvm.so or jvm.dll.

The following changes are made:
   The source for these methods is placed in the jdk.incubator.vector module under src/jdk.incubator.vector/linux/native/libsvml and src/jdk.incubator.vector/windows/native/libsvml.
   The assembly source files are named as “*.S” and include files are named as “*.S.inc”.
   The corresponding build script is placed at make/modules/jdk.incubator.vector/Lib.gmk.
   Changes are made to build system to support dependency tracking for assembly files with includes.
   The built native libraries (libsvml.so/svml.dll) are placed in bin directory of JDK on Windows and lib directory of JDK on Linux.
   The C2 JIT uses the dll_load and dll_lookup to get the addresses of optimized methods from this library.

Build system changes and module library build scripts are contributed by Magnus Ihse Bursie (ihse@openjdk.org).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264321](https://bugs.openjdk.java.net/browse/JDK-8264321): Create a separate library for x86 Intel SVML assembly intrinsics

### Reviewers
 * [Paul Sandoz](https://openjdk.java.net/census#psandoz) (@PaulSandoz - Committer)

### Contributors
 * Magnus Ihse Bursie `<ihse@openjdk.org>`
 * Sandhya Viswanathan `<sviswanathan@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/panama-vector pull/53/head:pull/53` \
`$ git checkout pull/53`

Update a local copy of the PR: \
`$ git checkout pull/53` \
`$ git pull https://git.openjdk.java.net/panama-vector pull/53/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 53`

View PR using the GUI difftool: \
`$ git pr show -t 53`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/panama-vector/pull/53.diff">https://git.openjdk.java.net/panama-vector/pull/53.diff</a>

</details>

### CODE REVIEW

**Review by PaulSandoz — APPROVED** [review]
I presume this is partially related to https://github.com/openjdk/jdk/pull/3198 ?

**Comment by sviswa7** [comment]
@PaulSandoz  Yes openjdk/jdk#3198 is related to this.

**Comment by sviswa7** [comment]
@PaulSandoz We only had the Linux and Windows assembly for svml in panama-vector so only those were converted to library.

**Comment by PaulSandoz** [comment]
@sviswa7 do you think this is something we could add and include as part of the JEP, or would it require more work?

**Comment by sviswa7** [comment]
@PaulSandoz  It will need more work so let us keep it to Linux and Windows for now.

**Pull request closed without merging**
