### PR TITLE
8265482: [vector] loading/storing byte vector from/to boolean[]

### PR DESCRIPTION
**Pull request by PaulSandoz**
Add methods to load/store a byte vector from/to boolean[].

A boolean value is converted to a byte value by way of the expression (byte) b ? 1 : 0, where b is the boolean value.

A byte value is converted to a boolean value by way of the expression (b & 1) != 0 ? true : false, where b is the byte value.

The testing is partially covered. Further tests need to be added for gather/scatter load/stores. However, existing gather/scatter tests are not part of the load/store test templates, and i would like to make that so before adding such tests.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Issue
 * [JDK-8265482](https://bugs.openjdk.java.net/browse/JDK-8265482): [vector] loading/storing byte vector from/to boolean[]

### Reviewers
 * [Sandhya Viswanathan](https://openjdk.java.net/census#sviswanathan) (@sviswa7 - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/panama-vector pull/71/head:pull/71` \
`$ git checkout pull/71`

Update a local copy of the PR: \
`$ git checkout pull/71` \
`$ git pull https://git.openjdk.java.net/panama-vector pull/71/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 71`

View PR using the GUI difftool: \
`$ git pr show -t 71`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/panama-vector/pull/71.diff">https://git.openjdk.java.net/panama-vector/pull/71.diff</a>

</details>

### CODE REVIEW

**Comment by sviswa7** [comment]
Looks good to me.

**Review by sviswa7 — APPROVED** [review]

**Comment by iwanowww** [comment]
> A byte value is converted to a boolean value by way of the expression (b & 1) != 0 ? true : false, where b is the byte value.

I'm curious what's the motivation for relying on `(b & 1) != 0` instead of `b != 0`?

**Comment by PaulSandoz** [comment]
> > A byte value is converted to a boolean value by way of the expression (b & 1) != 0 ? true : false, where b is the byte value.
> 
> I'm curious what's the motivation for relying on `(b & 1) != 0` instead of `b != 0`?

I was motivated by what i understood to be the HotSpot's internal representation, so we can do `ByteVector normalized = this.and((byte) 1);`, then store the contents of `normalized` vector directly to memory location of the `boolean[]` array.

Alternatively we could perform a non-zero test to obtain a mask then store the mask, but mask stores to `boolean[]` are not currently intrinsic. Potential to adjust the specification later maybe?

**Pull request closed without merging**
