### PR TITLE
8271009: AArch64: Wrap duplicated SVE instructions into a single method

### PR DESCRIPTION
**Pull request by e1iu**
This patch is a small cleanup. Since most of the usage of 'sve_whilelo'
are a pair of 'mov' and 'whilelo', this patch wraps them as a single
method.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Issue
 * [JDK-8271009](https://bugs.openjdk.java.net/browse/JDK-8271009): AArch64: Wrap duplicated SVE instructions into a single method

### Reviewers
 * [Ningsheng Jian](https://openjdk.java.net/census#njian) (@nsjian - Committer)
 * [Xiaohong Gong](https://openjdk.java.net/census#xgong) (@XiaohongGong - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/panama-vector pull/101/head:pull/101` \
`$ git checkout pull/101`

Update a local copy of the PR: \
`$ git checkout pull/101` \
`$ git pull https://git.openjdk.java.net/panama-vector pull/101/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 101`

View PR using the GUI difftool: \
`$ git pr show -t 101`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/panama-vector/pull/101.diff">https://git.openjdk.java.net/panama-vector/pull/101.diff</a>

</details>

### CODE REVIEW

**Review by nsjian — APPROVED** [review]
Looks good. Thanks!

**Review by XiaohongGong — APPROVED** [review]
Looks good to me! Thanks!

**Pull request closed without merging**
