### PR TITLE
Merge panama-vector:vector-unstable

### PR DESCRIPTION
**Pull request by nsjian**
Merge

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Reviewers
 * [Paul Sandoz](https://openjdk.java.net/census#psandoz) (@PaulSandoz - Committer) ⚠️ Review applies to bf3d59c4d894e8ca1e54aa890a01114beaab5286

### Download
`$ git fetch https://git.openjdk.java.net/panama-vector pull/4/head:pull/4`
`$ git checkout pull/4`

### CODE REVIEW

**Comment by nsjian** [comment]
This is a clean merge, no conflicts.

**Review by PaulSandoz — APPROVED** [review]

**Comment by PaulSandoz** [comment]
@nsjian thank you for your understanding and working on `vectorIntrinsics` for now. Once we integrate the Vector API i hope we can follow up quickly.

**Comment by nsjian** [comment]
@PaulSandoz any idea how can I merge this? The jcheck always reports error. Either:

"Merge commit message is not Merge, but: Merge panama-vector:vector-unstable",

or

"Could not determine the source for this merge.  A Merge PR title must be specified on the format: Merge project:branch to allow verification of the merge contents."

**Comment by PaulSandoz** [comment]
@nsjian I think there is an issue with the contents of the [.jcheck/conf](https://github.com/openjdk/panama-vector/blob/master/.jcheck/conf#L19) file. The `[Merge]` check message might need to be "message=Merge .*".

See this change made to the panama-foreign repo: https://github.com/openjdk/panama-foreign/commit/64294f3000e961cf4820cbc1189269258d782290#diff-916bf78a0828e8bef329c874c16980bf

**Comment by nsjian** [comment]
> I am checking with other engineers.

**Comment by nsjian** [comment]
> See this change made to the panama-foreign repo: [openjdk/panama-foreign@64294f3#diff-916bf78a0828e8bef329c874c16980bf](https://github.com/openjdk/panama-foreign/commit/64294f3000e961cf4820cbc1189269258d782290#diff-916bf78a0828e8bef329c874c16980bf)
> 
> I am checking with other engineers.

Thanks!

**Comment by nsjian** [comment]
I have rebased my code, but the jcheck still failed.

**Comment by PaulSandoz** [comment]
@nsjian I updated the .jcheck/conf file again as recommended (direct push rather than go through the pull request ceremony). Can you try again?

**Comment by nsjian** [comment]
> @nsjian I updated the .jcheck/conf file again as recommended (direct push rather than go through the pull request ceremony). Can you try again?

@PaulSandoz Thanks! It works!

**Pull request closed without merging**
