### PR TITLE
Remove `byte[]` and `ByteBuffer` access methods.

### PR DESCRIPTION
**Pull request by PaulSandoz**
Removes `byte[]` and `ByteBuffer` vector access methods.

Fixes performance issue with the fallback implementation of `MemorySegment` accessors (the `ValueLayout` passed to the scalar accessors needs to be constant).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Reviewers
 * [Sandhya Viswanathan](https://openjdk.java.net/census#sviswanathan) (@sviswa7 - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/panama-vector pull/190/head:pull/190` \
`$ git checkout pull/190`

Update a local copy of the PR: \
`$ git checkout pull/190` \
`$ git pull https://git.openjdk.java.net/panama-vector pull/190/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 190`

View PR using the GUI difftool: \
`$ git pr show -t 190`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/panama-vector/pull/190.diff">https://git.openjdk.java.net/panama-vector/pull/190.diff</a>

</details>

### CODE REVIEW

**Comment by DamonFool** [comment]
Hi @PaulSandoz ,

Is there any perf number before and after this patch?
Also why there is no JBS for this PR?

**Comment by PaulSandoz** [comment]
Hi @DamonFool, issues are optional for integration into the `panama-vector` repo.

Performance-wise `MemorySegment` is similar to `byte[]` and `ByteBuffer` (heap and direct), which is not too surprising since the `base`/`offset` are extracted from a segment and passed to the `load`/`store` vector intrinsic.

There is one performance anomaly I have observed related to using an `int`-based loop and `int` offset. This results in a widening conversion to `long` when passing the `int` value as the `offset` argument to the access method. The memory addressing logic is not efficient, which exacerbates with unrolling. This may be more generally C2 related, but it requires further investigation.

**Comment by PaulSandoz** [comment]
@merykitty that's a good point. I have run into that before, and could be a likely cause.

**Comment by DamonFool** [comment]
> Hi @DamonFool, issues are optional for integration into the `panama-vector` repo.

Okay.

> 
> Performance-wise `MemorySegment` is similar to `byte[]` and `ByteBuffer` (heap and direct), which is not too surprising since the `base`/`offset` are extracted from a segment and passed to the `load`/`store` vector intrinsic.
> 
> There is one performance anomaly I have observed related to using an `int`-based loop and `int` offset. This results in a widening conversion to `long` when passing the `int` value as the `offset` argument to the access method. The memory addressing logic is not efficient, which exacerbates with unrolling. This may be more generally C2 related, but it requires further investigation.

Can you give us a benchmark example whose performance would be improved so that we can learn more from your patch?
Thanks.

**Comment by PaulSandoz** [comment]
@DamonFool I confirmed what @merykitty described, related to overflow, although I suppose if the loop bound is known then it could be determined if overflow occurs or not. Although, as i understand this area of HotSpot is quite tricky.

If doing a calculation such as `someIntIndex << 2` it is necessary to explicitly cast `someIntIndex` to a `long`, similar to what is required when using `Unsafe` e.g. see [here](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/concurrent/ConcurrentHashMap.java#L760). The alternative is to use a `long` based index.

**Review by sviswa7 — APPROVED** [review]
Looks good to me.

**Pull request closed without merging**
