### PR TITLE
8267368: Add masking support for reduction vector intrinsics

### PR DESCRIPTION
**Pull request by XiaohongGong**
This patch adds the masking support for vector reduction operations, including the Vector API java implementation and hotspot intrinsics changes. It adds the mask information to the reduction intrinsic method. With it:
  - Both masked and non-masked reduction operations call the same hotspot intrinsics. The mask value and class are set to `"null"` for non-masked operations.
  - Reduction IR with mask as another input will be generated if the platform supports the predicate feature for the op. Otherwise, the vector blend pattern will be generated like before.

Note that this patch only contains the Vector API java implementation and the hotspot intrinsics changes. No compiler mid-end and backend implementations are included.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Issue
 * [JDK-8267368](https://bugs.openjdk.java.net/browse/JDK-8267368): Add masking support for reduction vector intrinsics

### Reviewers
 * [Paul Sandoz](https://openjdk.java.net/census#psandoz) (@PaulSandoz - Committer) ⚠️ Review applies to e1e0c44cb48350dda87f3303e0e7469c8d024a67

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/panama-vector pull/86/head:pull/86` \
`$ git checkout pull/86`

Update a local copy of the PR: \
`$ git checkout pull/86` \
`$ git pull https://git.openjdk.java.net/panama-vector pull/86/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 86`

View PR using the GUI difftool: \
`$ git pr show -t 86`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/panama-vector/pull/86.diff">https://git.openjdk.java.net/panama-vector/pull/86.diff</a>

</details>

### CODE REVIEW

**Comment by XiaohongGong** [comment]
Hi @PaulSandoz @iwanowww , would you mind taking a look at the masking support part for the vector reduction operations? Thanks so much! Any feedback is welcome!

**Review by PaulSandoz — APPROVED** [review]
Looks good.

**Comment by XiaohongGong** [comment]
> Looks good.

Thanks for your review @PaulSandoz !

**Comment by XiaohongGong** [comment]
Hi @iwanowww, may I have your kindly feedback to the compiler side for this PR please? Thanks so much!

**Comment by XiaohongGong** [comment]
Hi @iwanowww , any feedback to the compiler changes? Thanks so much!

**Comment by XiaohongGong** [comment]
Hi @iwanowww , we'd like to integrate this PR first to promote the further masking feature development. Any comments and feedback are still welcome! And we can revisit them in future. Thanks so much!

Best Regards,
Xiaohong

**Pull request closed without merging**
