### PR TITLE
Merge panama-vector:master

### PR DESCRIPTION
**Pull request by jatin-bhateja**
- Merge panama-vector:master into vectorIntrinsics.
- Validation done using vector API JTREGs at different AVX levels.

Kindly review and approve.

Regards,
Jatin

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Reviewers
 * [Sandhya Viswanathan](https://openjdk.java.net/census#sviswanathan) (@sviswa7 - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/panama-vector pull/183/head:pull/183` \
`$ git checkout pull/183`

Update a local copy of the PR: \
`$ git checkout pull/183` \
`$ git pull https://git.openjdk.java.net/panama-vector pull/183/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 183`

View PR using the GUI difftool: \
`$ git pr show -t 183`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/panama-vector/pull/183.diff">https://git.openjdk.java.net/panama-vector/pull/183.diff</a>

</details>

### CODE REVIEW

**Comment by jatin-bhateja** [comment]
Hi @nsjian , @XiaohongGong , @theRealELiu , 
Can you kindly approve, I understand we have few inflight patches which may need a rebase after this.

**Comment by nsjian** [comment]
> Hi @nsjian , @XiaohongGong , @theRealELiu , Can you kindly approve, I understand we have few inflight patches which may need a rebase after this but their reviews may take some time.

Thanks for your work! I think "test/hotspot/gtest/aarch64/asm-test.out.h" needs to be regenerated by "$ python aarch64-asmtest.py | expand > ./asmtest.out.h". Are you able to do that? If not, I can generate it for you, but it seems that there are some conflicts after @XiaohongGong 's recent merge...

**Comment by nsjian** [comment]
> > Hi @nsjian , @XiaohongGong , @theRealELiu , Can you kindly approve, I understand we have few inflight patches which may need a rebase after this but their reviews may take some time.
> 
> Thanks for your work! I think "test/hotspot/gtest/aarch64/asmtest.out.h" needs to be regenerated by "$ python aarch64-asmtest.py | expand > ./asmtest.out.h". Are you able to do that? If not, I can generate it for you. But it seems that there are some conflicts after @XiaohongGong 's recent merge...

I did a merge of your patch with latest vectorIntrinsics again. Regenerated the file and sent it to you.

**Comment by jatin-bhateja** [comment]
> > > Hi @nsjian , @XiaohongGong , @theRealELiu , Can you kindly approve, I understand we have few inflight patches which may need a rebase after this but their reviews may take some time.
> > 
> > 
> > Thanks for your work! I think "test/hotspot/gtest/aarch64/asmtest.out.h" needs to be regenerated by "$ python aarch64-asmtest.py | expand > ./asmtest.out.h". Are you able to do that? If not, I can generate it for you. But it seems that there are some conflicts after @XiaohongGong 's recent merge...
> 
> I did a merge of your patch with latest vectorIntrinsics again. Regenerated the file and sent it to you.

Thanks I have updated the patch with latest changes.

**Review by sviswa7 — APPROVED** [review]

**Pull request closed without merging**
