### PR TITLE
8282942: [vector] Trivial code style updates

### PR DESCRIPTION
**Pull request by XiaohongGong**
This patch mainly fixes some code style issues in the Vector API java codes and the test codes, e.g. adding the missing spaces for some statements.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Issue
 * [JDK-8282942](https://bugs.openjdk.java.net/browse/JDK-8282942): [vector] Trivial code style updates

### Reviewers
 * [Paul Sandoz](https://openjdk.java.net/census#psandoz) (@PaulSandoz - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/panama-vector pull/179/head:pull/179` \
`$ git checkout pull/179`

Update a local copy of the PR: \
`$ git checkout pull/179` \
`$ git pull https://git.openjdk.java.net/panama-vector pull/179/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 179`

View PR using the GUI difftool: \
`$ git pr show -t 179`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/panama-vector/pull/179.diff">https://git.openjdk.java.net/panama-vector/pull/179.diff</a>

</details>

### CODE REVIEW

**Review by PaulSandoz — COMMENTED** [review]
Can you please target the jdk repository then we can do a merge? Otherwise its going to make reviewing new code more difficult.

**Comment by nsjian** [comment]
> Can you please target the jdk repository then we can do a merge? Otherwise its going to make reviewing new code more difficult.

Yeah. Suggest to make those vectorIntrinsics specific style changes here.

**Comment by XiaohongGong** [comment]
> > Can you please target the jdk repository then we can do a merge? Otherwise its going to make reviewing new code more difficult.
> 
> Yeah. Suggest to make those vectorIntrinsics specific style changes here.

Sounds good to me. I will only fix the new added codes on vectorIntrinsics. Thanks for your review @PaulSandoz  @nsjian !

**Pull request closed without merging**
