### PR TITLE
Merge panama-vector:vectorIntrinsics

### PR DESCRIPTION
**Pull request by jatin-bhateja**
Following two files have merge conflicts
- src/hotspot/cpu/aarch64/aarch64_sve_ad.m4
- src/hotspot/cpu/aarch64/aarch64_sve.ad

@nsjian, @theRealELiu , @XiaohongGong 
Can you kindly resolve the conflicts.

Thanks

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Contributors
 * Ningsheng Jian `<njian@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/panama-vector pull/112/head:pull/112` \
`$ git checkout pull/112`

Update a local copy of the PR: \
`$ git checkout pull/112` \
`$ git pull https://git.openjdk.java.net/panama-vector pull/112/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 112`

View PR using the GUI difftool: \
`$ git pr show -t 112`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/panama-vector/pull/112.diff">https://git.openjdk.java.net/panama-vector/pull/112.diff</a>

</details>

### CODE REVIEW

**Comment by nsjian** [comment]
> Following two files have merge conflicts
> 
> * src/hotspot/cpu/aarch64/aarch64_sve_ad.m4
> * src/hotspot/cpu/aarch64/aarch64_sve.ad
> 
> @nsjian, @theRealELiu , @XiaohongGong
> Can you kindly resolve the conflicts.

This is the commit on top of your code, with conflicts resolved.

https://github.com/nsjian/panama-vector/commit/c01c135c66bc2cc5d867d3ee233029365b08c59d

**Comment by jatin-bhateja** [comment]
> > Following two files have merge conflicts
> > 
> > * src/hotspot/cpu/aarch64/aarch64_sve_ad.m4
> > * src/hotspot/cpu/aarch64/aarch64_sve.ad
> > 
> > @nsjian, @theRealELiu , @XiaohongGong
> > Can you kindly resolve the conflicts.
> 
> This is the commit on top of your code, with conflicts resolved.
> 
> [nsjian@c01c135](https://github.com/nsjian/panama-vector/commit/c01c135c66bc2cc5d867d3ee233029365b08c59d)

Thanks @nsjina, conflicts merged.

**Pull request closed without merging**
