### PR TITLE
Merge panama-vector:master

### PR DESCRIPTION
**Pull request by luhenry**
Merge latest master changes into vectorIntrinsics branch.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Reviewers
 * [Paul Sandoz](https://openjdk.java.net/census#psandoz) (@PaulSandoz - Committer)
 * [Sandhya Viswanathan](https://openjdk.java.net/census#sviswanathan) (@sviswa7 - Committer)

### Download
`$ git fetch https://git.openjdk.java.net/panama-vector pull/28/head:pull/28`
`$ git checkout pull/28`

### CODE REVIEW

**Review by PaulSandoz — APPROVED** [review]
I eyeballed the webrevs and it looks good to me (but not familiar with all HotSpot code)

**Review by sviswa7 — APPROVED** [review]

**Comment by sviswa7** [comment]
Looks good to me as well.

**Comment by PaulSandoz** [comment]
@luhenry are you going to integrate this?

**Comment by luhenry** [comment]
@PaulSandoz sorry it fell off my radar and I didn't get the notification.

**Pull request closed without merging**
