### PR TITLE
8273159: Remove LoadVectorMaskNode/StoreVectorMaskNode

### PR DESCRIPTION
**Pull request by nsjian**
Removed the nodes and related code. Try to generate the SVE ld1b/st1b extend/narrow instructions by matching specific rules.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Issue
 * [JDK-8273159](https://bugs.openjdk.java.net/browse/JDK-8273159): Remove LoadVectorMaskNode/StoreVectorMaskNode

### Reviewers
 * [Eric Liu](https://openjdk.java.net/census#eliu) (@theRealELiu - Committer)
 * sviswanathan - Committer ⚠️ Added manually

### Contributors
 * Xiaohong Gong `<xgong@openjdk.org>`
 * Ningsheng Jian `<njian@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/panama-vector pull/116/head:pull/116` \
`$ git checkout pull/116`

Update a local copy of the PR: \
`$ git checkout pull/116` \
`$ git pull https://git.openjdk.java.net/panama-vector pull/116/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 116`

View PR using the GUI difftool: \
`$ git pr show -t 116`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/panama-vector/pull/116.diff">https://git.openjdk.java.net/panama-vector/pull/116.diff</a>

</details>

### CODE REVIEW

**Review by theRealELiu — APPROVED** [review]
LGTM.

**Comment by nsjian** [comment]
Thank you @theRealELiu for the review! 

Hi @jatin-bhateja @sviswa7 , could you please help to take a look at shared code changes?

**Comment by sviswa7** [comment]
Shared code changes look good to me.

**Comment by nsjian** [comment]
Thank you @sviswa7!

/reviewer credit @sviswa7

**Pull request closed without merging**
