### PR TITLE
Merge panama-vector:master

### PR DESCRIPTION
**Pull request by PaulSandoz**
Merge master changes into vectorIntrinsics branch.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Reviewers
 * [Sandhya Viswanathan](https://openjdk.java.net/census#sviswanathan) (@sviswa7 - Committer) ⚠️ Review applies to 80db52fd8cc11ad2199a4339d7aa02344280f6a6

### Download
`$ git fetch https://git.openjdk.java.net/panama-vector pull/25/head:pull/25`
`$ git checkout pull/25`

### CODE REVIEW

**Review by sviswa7 — APPROVED** [review]

**Comment by PaulSandoz** [comment]
@nsjian I have almost certainly got the aarch64 changes wrong to that file which tests instructions for a debug build. Can you help with this? We can update the PR or we can integrate this PR as is, then follow up with a new PR with specific changes.

**Comment by nsjian** [comment]
> @nsjian I have almost certainly got the aarch64 changes wrong to that file which tests instructions for a debug build. Can you help with this? We can update the PR or we can integrate this PR as is, then follow up with a new PR with specific changes.

I will take a look later today.

**Comment by nsjian** [comment]
I think JDK-8253623 now has a proper fix in openjdk/jdk: https://github.com/openjdk/jdk/pull/853, which is included in this merge. So we don't need the workaround code from JDK-8253623.

**Comment by nsjian** [comment]
> @nsjian I have almost certainly got the aarch64 changes wrong to that file which tests instructions for a debug build. Can you help with this? We can update the PR or we can integrate this PR as is, then follow up with a new PR with specific changes.

@PaulSandoz Thanks for the work! I have fixed the aarch64 merge in https://github.com/PaulSandoz/panama-vector/pull/1

**Comment by PaulSandoz** [comment]
@nsjian many thanks, well spotted on JDK-8253623

**Pull request closed without merging**
