### PR TITLE
8263424: Extend vector size support for SVE

### PR DESCRIPTION
**Pull request by nsjian**
This patch adds support of vector operations with size less than MaxVectorSize for SVE. Basically, for general vector operations, we simply keep original operations, i.e. doing a full vector length operations, but for load/store and reduction operations, we use
predicate operations to make sure only vector elements in the size limit are loaded/stored/calculated.

This patch also fixes an SVE load/store addressing mode usage issue. For SVE load/store scalar plus immediate, the immediate displacements are calculated by both vector element size and memory element size. As the existing vmemA_immIOffset4 and vmemA_immLOffset4 does not take into account of the vector and memory element size difference, we should not use them for extend/narrow forms.

Tested with tier1 and jdk:tier3. jdk/incubator/vector cases have also been verified with different MaxVectorSize options.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263424](https://bugs.openjdk.java.net/browse/JDK-8263424): Extend vector size support for SVE

### Reviewers
 * [Xiaohong Gong](https://openjdk.java.net/census#xgong) (@XiaohongGong - Committer)
 * [Wang Huang](https://openjdk.java.net/census#whuang) (@Wanghuang-Huawei - Committer) ⚠️ Review applies to c41631946839b9526995d11077d19e7f8ed4551f

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/panama-vector pull/49/head:pull/49` \
`$ git checkout pull/49`

Update a local copy of the PR: \
`$ git checkout pull/49` \
`$ git pull https://git.openjdk.java.net/panama-vector pull/49/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 49`

View PR using the GUI difftool: \
`$ git pr show -t 49`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/panama-vector/pull/49.diff">https://git.openjdk.java.net/panama-vector/pull/49.diff</a>

</details>

### CODE REVIEW

**Review by XiaohongGong — APPROVED** [review]

**Comment by XiaohongGong** [comment]
LGTM, thanks!

**Comment by nsjian** [comment]
> LGTM, thanks!

Thank you Xiaohong! Can I get a review/approval from a committer? Perhaps @PaulSandoz ? :-)

**Comment by PaulSandoz** [comment]
@nsjian to be honest i don't feel confident reviewing ARM-specific code.
Do you have other colleagues with a panama committer role that can review?
May i suggest that you nominate @XiaohongGong for a committer role in Panama?

**Comment by nsjian** [comment]
> @nsjian to be honest i don't feel confident reviewing ARM-specific code.
> Do you have other colleagues with a panama committer role that can review?
> May i suggest that you nominate @XiaohongGong for a committer role in Panama?

I don't have other colleagues with panama committer role. I will nominate @XiaohongGong later. I would expect the process may take some time.

**Comment by nsjian** [comment]
Clicked the wrong button... Reopen this.

**Comment by Wanghuang-Huawei** [comment]
LGTM. Thank you for your work.

**Review by Wanghuang-Huawei — APPROVED** [review]

**Comment by nsjian** [comment]
@XiaohongGong @Wanghuang-Huawei Thanks for the review! I have resolved the merge conflicts.

**Review by XiaohongGong — APPROVED** [review]

**Pull request closed without merging**
